`timescale 1ns/1ps

import risc_pkg::*;

module top #(
  parameter RESET_PC = 32'h0000
)(
  input logic clk,
  input logic reset_n
);

  localparam logic [31:0] NOP_INSTRUCTION = 32'h0000_0013;

  // Instruction memory wires: connect fetch PC to instruction memory.
  logic        instruction_memory_request;
  logic [31:0] instruction_memory_address;
  logic [31:0] instruction_memory_read_data;

  // Data memory wire: carries MEM-stage load data into the WB stage.
  logic [31:0] data_memory_read_data;

  // IF stage wires: hold current PC, selected next PC, PC+4, and fetched instruction.
  logic [31:0] current_pc;
  logic [31:0] next_pc_to_load;
  logic [31:0] current_pc_plus4;
  logic [31:0] fetched_instruction;

  // IF/ID pipeline register wires: carry fetched instruction and its PC into decode.
  logic [31:0] if_id_pc_value;
  logic [31:0] if_id_pc_plus4_value;
  logic [31:0] if_id_instruction;

  // ID stage wires: decoded instruction fields.
  logic [6:0]  decoded_opcode;
  logic [2:0]  decoded_funct3;
  logic [6:0]  decoded_funct7;
  logic [4:0]  decoded_rs1_addr;
  logic [4:0]  decoded_rs2_addr;
  logic [4:0]  decoded_rd_addr;

  // ID stage wires: register reads and immediate generation.
  logic [31:0] decoded_rs1_data;
  logic [31:0] decoded_rs2_data;
  logic [31:0] decoded_immediate;

  // ID stage wires: instruction format flags.
  logic        decoded_is_r_type;
  logic        decoded_is_i_type;
  logic        decoded_is_s_type;
  logic        decoded_is_b_type;
  logic        decoded_is_u_type;
  logic        decoded_is_j_type;
  logic        decoded_uses_rs1;
  logic        decoded_uses_rs2;

  // ID stage wires: control signals generated by the control unit.
  logic        decoded_is_jump;
  logic        decoded_select_pc_as_alu_a;
  logic        decoded_select_immediate_as_alu_b;
  alu_op_t     decoded_alu_operation;
  wb_src_t     decoded_writeback_source;
  logic        decoded_memory_request;
  mem_size_t   decoded_memory_size;
  logic        decoded_memory_write_enable;
  logic        decoded_load_zero_extend;
  logic        decoded_register_write_enable;

  // ID/EX pipeline register wires: carry decoded data and control into execute.
  logic [31:0] execute_pc_value;
  logic [31:0] execute_pc_plus4_value;
  logic [31:0] execute_rs1_data;
  logic [31:0] execute_rs2_data;
  logic [31:0] execute_immediate;
  logic [4:0]  execute_rs1_addr;
  logic [4:0]  execute_rs2_addr;
  logic [4:0]  execute_rd_addr;
  logic [2:0]  execute_funct3;
  logic        execute_is_b_type;
  logic        execute_is_jump;
  logic        execute_select_pc_as_alu_a;
  logic        execute_select_immediate_as_alu_b;
  alu_op_t     execute_alu_operation;
  wb_src_t     execute_writeback_source;
  logic        execute_memory_request;
  mem_size_t   execute_memory_size;
  logic        execute_memory_write_enable;
  logic        execute_load_zero_extend;
  logic        execute_register_write_enable;

  // EX stage wires: forwarded operand values selected by hazard_control.
  logic [31:0] execute_rs1_value_after_forwarding;
  logic [31:0] execute_rs2_value_after_forwarding;

  // EX stage wires: ALU inputs, ALU result, branch target, and redirect decision.
  logic [31:0] execute_alu_operand_a;
  logic [31:0] execute_alu_operand_b;
  logic [31:0] execute_alu_result;
  logic [31:0] execute_branch_or_jump_target;
  logic        execute_branch_taken;
  logic        execute_redirect_pc;

  // EX/MEM pipeline register wires: carry execute results and memory controls into MEM.
  logic [31:0] memory_alu_result;
  logic [31:0] memory_store_write_data;
  logic [31:0] memory_immediate;
  logic [31:0] memory_pc_plus4_value;
  logic [4:0]  memory_rd_addr;
  wb_src_t     memory_writeback_source;
  logic        memory_request;
  mem_size_t   memory_access_size;
  logic        memory_write_enable;
  logic        memory_load_zero_extend;
  logic        memory_register_write_enable;

  // MEM/WB pipeline register wires: carry final writeback candidates into WB.
  logic [31:0] writeback_alu_result;
  logic [31:0] writeback_memory_read_data;
  logic [31:0] writeback_immediate;
  logic [31:0] writeback_pc_plus4_value;
  logic [4:0]  writeback_rd_addr;
  wb_src_t     writeback_data_source;
  logic        writeback_register_write_enable;

  // WB stage wire: final value written into the register file.
  logic [31:0] register_file_write_data;

  // Hazard unit wire: freezes IF/ID and inserts an execute bubble for load-use hazards.
  logic        stall_for_load_use_hazard;

  fetch #(
    .RESET_PC (RESET_PC)
  ) u_fetch (
    .clk                           (clk),
    .reset_n                       (reset_n),
    .next_pc                       (next_pc_to_load),
    .instruction_memory_read_data  (instruction_memory_read_data),
    .instruction_memory_request    (instruction_memory_request),
    .instruction_memory_address    (instruction_memory_address),
    .current_pc                    (current_pc),
    .current_pc_plus4              (current_pc_plus4),
    .fetched_instruction           (fetched_instruction)
  );

  instruction_memory u_instruction_memory (
    .imem_req   (instruction_memory_request),
    .imem_addr  (instruction_memory_address),
    .imem_data  (instruction_memory_read_data)
  );

  decode u_decode (
    .instruction (if_id_instruction),
    .rs1_addr    (decoded_rs1_addr),
    .rs2_addr    (decoded_rs2_addr),
    .rd_addr     (decoded_rd_addr),
    .opcode      (decoded_opcode),
    .funct3      (decoded_funct3),
    .funct7      (decoded_funct7),
    .r_type      (decoded_is_r_type),
    .i_type      (decoded_is_i_type),
    .s_type      (decoded_is_s_type),
    .b_type      (decoded_is_b_type),
    .u_type      (decoded_is_u_type),
    .j_type      (decoded_is_j_type),
    .uses_rs1    (decoded_uses_rs1),
    .uses_rs2    (decoded_uses_rs2)
  );

  extend u_extend (
    .instruction (if_id_instruction),
    .r_type      (decoded_is_r_type),
    .i_type      (decoded_is_i_type),
    .s_type      (decoded_is_s_type),
    .b_type      (decoded_is_b_type),
    .u_type      (decoded_is_u_type),
    .immediate   (decoded_immediate)
  );

  control u_control (
    .r_type             (decoded_is_r_type),
    .i_type             (decoded_is_i_type),
    .s_type             (decoded_is_s_type),
    .b_type             (decoded_is_b_type),
    .u_type             (decoded_is_u_type),
    .j_type             (decoded_is_j_type),
    .funct3             (decoded_funct3),
    .funct7             (decoded_funct7),
    .opcode             (decoded_opcode),
    .pc_sel             (decoded_is_jump),
    .op1_sel            (decoded_select_pc_as_alu_a),
    .op2_sel            (decoded_select_immediate_as_alu_b),
    .alu_op             (decoded_alu_operation),
    .rf_wr_data_sel     (decoded_writeback_source),
    .dmem_req           (decoded_memory_request),
    .dmem_size          (decoded_memory_size),
    .dmem_wr_en         (decoded_memory_write_enable),
    .dmem_zero_extend   (decoded_load_zero_extend),
    .rf_wr_en           (decoded_register_write_enable)
  );

  register_file u_register_file (
    .clk       (clk),
    .reset_n   (reset_n),
    .rs1_addr  (decoded_rs1_addr),
    .rs2_addr  (decoded_rs2_addr),
    .rd_addr   (writeback_rd_addr),
    .rf_wr_en  (writeback_register_write_enable),
    .wr_data   (register_file_write_data),
    .rs1_data  (decoded_rs1_data),
    .rs2_data  (decoded_rs2_data)
  );

  assign execute_alu_operand_a = execute_select_pc_as_alu_a ?
                                 execute_pc_value :
                                 execute_rs1_value_after_forwarding;

  assign execute_alu_operand_b = execute_select_immediate_as_alu_b ?
                                 execute_immediate :
                                 execute_rs2_value_after_forwarding;

  alu u_alu (
    .alu_a   (execute_alu_operand_a),
    .alu_b   (execute_alu_operand_b),
    .alu_op  (execute_alu_operation),
    .alu_res (execute_alu_result)
  );

  branch_control u_branch_control (
    .opr_a         (execute_rs1_value_after_forwarding),
    .opr_b         (execute_rs2_value_after_forwarding),
    .is_b_type     (execute_is_b_type),
    .funct3        (execute_funct3),
    .branch_taken  (execute_branch_taken)
  );

  assign execute_branch_or_jump_target = {execute_alu_result[31:1], 1'b0};

  data_memory u_data_memory (
    .clk               (clk),
    .dmem_req          (memory_request),
    .dmem_wr_en        (memory_write_enable),
    .dmem_data_size    (memory_access_size),
    .dmem_addr         (memory_alu_result),
    .dmem_wr_data      (memory_store_write_data),
    .dmem_zero_extend  (memory_load_zero_extend),
    .dmem_rd_data      (data_memory_read_data)
  );

  always_comb begin
    case (writeback_data_source)
      WB_SRC_ALU: register_file_write_data = writeback_alu_result;
      WB_SRC_MEM: register_file_write_data = writeback_memory_read_data;
      WB_SRC_IMM: register_file_write_data = writeback_immediate;
      WB_SRC_PC:  register_file_write_data = writeback_pc_plus4_value;
      default:    register_file_write_data = 32'd0;
    endcase
  end

  hazard_control u_hazard_control (
    .id_rs1_addr            (decoded_rs1_addr),
    .id_rs2_addr            (decoded_rs2_addr),
    .id_uses_rs1            (decoded_uses_rs1),
    .id_uses_rs2            (decoded_uses_rs2),
    .id_ex_rs1_data         (execute_rs1_data),
    .id_ex_rs2_data         (execute_rs2_data),
    .id_ex_rs1_addr         (execute_rs1_addr),
    .id_ex_rs2_addr         (execute_rs2_addr),
    .id_ex_rd_addr          (execute_rd_addr),
    .id_ex_dmem_req         (execute_memory_request),
    .id_ex_dmem_wr_en       (execute_memory_write_enable),
    .id_ex_rf_wr_en         (execute_register_write_enable),
    .id_ex_pc_sel           (execute_is_jump),
    .ex_mem_alu_res         (memory_alu_result),
    .ex_mem_immediate       (memory_immediate),
    .ex_mem_pc_plus4        (memory_pc_plus4_value),
    .ex_mem_rd_addr         (memory_rd_addr),
    .ex_mem_rf_wr_data_sel  (memory_writeback_source),
    .ex_mem_dmem_req        (memory_request),
    .ex_mem_rf_wr_en        (memory_register_write_enable),
    .wb_wr_data             (register_file_write_data),
    .mem_wb_rd_addr         (writeback_rd_addr),
    .mem_wb_rf_wr_en        (writeback_register_write_enable),
    .ex_branch_taken        (execute_branch_taken),
    .ex_branch_target       (execute_branch_or_jump_target),
    .pc                     (current_pc),
    .next_seq_pc            (current_pc_plus4),
    .ex_rs1_fwd_data        (execute_rs1_value_after_forwarding),
    .ex_rs2_fwd_data        (execute_rs2_value_after_forwarding),
    .load_use_stall         (stall_for_load_use_hazard),
    .ex_take_pc             (execute_redirect_pc),
    .next_pc                (next_pc_to_load)
  );

  always_ff @(posedge clk or negedge reset_n) begin
    if (!reset_n) begin
      if_id_pc_value       <= RESET_PC;
      if_id_pc_plus4_value <= RESET_PC + 32'd4;
      if_id_instruction    <= NOP_INSTRUCTION;
    end
    else if (execute_redirect_pc) begin
      if_id_pc_value       <= 32'd0;
      if_id_pc_plus4_value <= 32'd0;
      if_id_instruction    <= NOP_INSTRUCTION;
    end
    else if (!stall_for_load_use_hazard) begin
      if_id_pc_value       <= current_pc;
      if_id_pc_plus4_value <= current_pc_plus4;
      if_id_instruction    <= fetched_instruction;
    end
  end

  always_ff @(posedge clk or negedge reset_n) begin
    if (!reset_n || execute_redirect_pc || stall_for_load_use_hazard) begin
      execute_pc_value                  <= 32'd0;
      execute_pc_plus4_value            <= 32'd0;
      execute_rs1_data                  <= 32'd0;
      execute_rs2_data                  <= 32'd0;
      execute_immediate                 <= 32'd0;
      execute_rs1_addr                  <= 5'd0;
      execute_rs2_addr                  <= 5'd0;
      execute_rd_addr                   <= 5'd0;
      execute_funct3                    <= 3'd0;
      execute_is_b_type                 <= 1'b0;
      execute_is_jump                   <= 1'b0;
      execute_select_pc_as_alu_a        <= 1'b0;
      execute_select_immediate_as_alu_b <= 1'b0;
      execute_alu_operation             <= ADD;
      execute_writeback_source          <= WB_SRC_ALU;
      execute_memory_request            <= 1'b0;
      execute_memory_size               <= WORD;
      execute_memory_write_enable       <= 1'b0;
      execute_load_zero_extend          <= 1'b0;
      execute_register_write_enable     <= 1'b0;
    end
    else begin
      execute_pc_value                  <= if_id_pc_value;
      execute_pc_plus4_value            <= if_id_pc_plus4_value;
      execute_rs1_data                  <= decoded_rs1_data;
      execute_rs2_data                  <= decoded_rs2_data;
      execute_immediate                 <= decoded_immediate;
      execute_rs1_addr                  <= decoded_rs1_addr;
      execute_rs2_addr                  <= decoded_rs2_addr;
      execute_rd_addr                   <= decoded_rd_addr;
      execute_funct3                    <= decoded_funct3;
      execute_is_b_type                 <= decoded_is_b_type;
      execute_is_jump                   <= decoded_is_jump;
      execute_select_pc_as_alu_a        <= decoded_select_pc_as_alu_a;
      execute_select_immediate_as_alu_b <= decoded_select_immediate_as_alu_b;
      execute_alu_operation             <= decoded_alu_operation;
      execute_writeback_source          <= decoded_writeback_source;
      execute_memory_request            <= decoded_memory_request;
      execute_memory_size               <= decoded_memory_size;
      execute_memory_write_enable       <= decoded_memory_write_enable;
      execute_load_zero_extend          <= decoded_load_zero_extend;
      execute_register_write_enable     <= decoded_register_write_enable;
    end
  end

  always_ff @(posedge clk or negedge reset_n) begin
    if (!reset_n) begin
      memory_alu_result            <= 32'd0;
      memory_store_write_data      <= 32'd0;
      memory_immediate             <= 32'd0;
      memory_pc_plus4_value        <= 32'd0;
      memory_rd_addr               <= 5'd0;
      memory_writeback_source      <= WB_SRC_ALU;
      memory_request               <= 1'b0;
      memory_access_size           <= WORD;
      memory_write_enable          <= 1'b0;
      memory_load_zero_extend      <= 1'b0;
      memory_register_write_enable <= 1'b0;
    end
    else begin
      memory_alu_result            <= execute_alu_result;
      memory_store_write_data      <= execute_rs2_value_after_forwarding;
      memory_immediate             <= execute_immediate;
      memory_pc_plus4_value        <= execute_pc_plus4_value;
      memory_rd_addr               <= execute_rd_addr;
      memory_writeback_source      <= execute_writeback_source;
      memory_request               <= execute_memory_request;
      memory_access_size           <= execute_memory_size;
      memory_write_enable          <= execute_memory_write_enable;
      memory_load_zero_extend      <= execute_load_zero_extend;
      memory_register_write_enable <= execute_register_write_enable;
    end
  end

  always_ff @(posedge clk or negedge reset_n) begin
    if (!reset_n) begin
      writeback_alu_result            <= 32'd0;
      writeback_memory_read_data      <= 32'd0;
      writeback_immediate             <= 32'd0;
      writeback_pc_plus4_value        <= 32'd0;
      writeback_rd_addr               <= 5'd0;
      writeback_data_source           <= WB_SRC_ALU;
      writeback_register_write_enable <= 1'b0;
    end
    else begin
      writeback_alu_result            <= memory_alu_result;
      writeback_memory_read_data      <= data_memory_read_data;
      writeback_immediate             <= memory_immediate;
      writeback_pc_plus4_value        <= memory_pc_plus4_value;
      writeback_rd_addr               <= memory_rd_addr;
      writeback_data_source           <= memory_writeback_source;
      writeback_register_write_enable <= memory_register_write_enable;
    end
  end

endmodule
